### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by sumgr0** [hahwul/s3reverse#1]
Getting the below error when running the intended installation command:
go get -u github.com/hahwul/s3reverse
package github.com/hahwul/s3reverse: no Go files in /root/go/src/github.com/hahwul/s3reverse

**Comment by sumgr0** [comment]
Fixed...edited the main.go
package s3reverse to package main
and then ran: go get -u github.com/sumgr0/s3reverse/cmd/s3reverse

**Comment by hahwul** [comment]
Oh, I remember it was designated as the main package, but now I see the code is S3reverse. I changed the same thing! Thank you for sending me the issue!
https://github.com/hahwul/s3reverse/commit/645580bee15743b4fb65764b6cfc13d161a12d35

**Comment by xElkomy** [comment]
> Fixed...edited the main.go
> package s3reverse to package main
> and then ran: go get -u github.com/sumgr0/s3reverse/cmd/s3reverse

thanks very much
