### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ddervosj** [hahwul/s3reverse#2]
Hello,

I'm using -verify to check a number of potential buckets, but receiving below error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x65be1c]

Any idea whats causing this?
Cheers

**Comment by hahwul** [comment]
Hi, @ddervosj 
Given that it's an `invalid memory address or a nil pointer reference` it's a bug, can you share a little bit more information?

For example, OS version, environment, and so on.

And if it's an environmental problem, you can create a binary that fits your current drive with `go build main.go`.

**Comment by ddervosj** [comment]
18.04.1-Ubuntu x64
go version go1.13.5 linux/amd64

It seems it only happens with larger files (>10mb). I'll try and test the go build solution.

**Comment by hahwul** [comment]
@ddervosj 
Thank you! I'll try to test it with 10Mb file. If the size of the file is a problem, it is likely to be a universally known issue in the golang and likely to be resolved. The information was very helpful. Thank you very much!

**Comment by hahwul** [comment]
## test log
### some file (SecLists/Discovery/DNS)
```
$ ll
total 73448
...
-rw-r--r--  1 hahwul  staff    25M 12 26 13:15 dns-Jhaddix.txt
```

verify
```
$ ~/go/bin/s3reverse -iL dns-Jhaddix.txt -verify
[NoSuchBucket] s3.amazonaws.com.timetrade.acmecorp
[NoSuchBucket] s3-eu-west-1.amazonaws.com.indianapolis.libproxy
[NoSuchBucket] s3.amazonaws.com.lib-ezproxy
[NoSuchBucket] s3.amazonaws.com.ezproxy.library
```

toAny
```
$ ~/go/bin/s3reverse -iL dns-Jhaddix.txt -tN
s3.amazonaws.com.ezproxy.library
s3.amazonaws.com.lib-ezproxy
s3.amazonaws.com.timetrade.acmecorp
s3-eu-west-1.amazonaws.com.indianapolis.libproxy

$ ~/go/bin/s3reverse -iL dns-Jhaddix.txt -tP
https://s3.amazonaws.com/s3.amazonaws.com.ezproxy.library
https://s3.amazonaws.com/s3.amazonaws.com.lib-ezproxy
https://s3.amazonaws.com/s3.amazonaws.com.timetrade.acmecorp
https://s3.amazonaws.com/s3-eu-west-1.amazonaws.com.indianapolis.libproxy
```

### only s3 format file
...

**Comment by popovicnenad** [comment]
Error was actually the result of `response.Body` being `nil` and doesn't have anything to do with file size. 
Response error was ignored explicitly, and `defer response.Body.close()`, even though execution is scheduled on func exit, would try to access body immediately.
Defer should always be defined after error check in cases like this.
